# Naive Bayes Using Sklearn

In [2]:
import numpy as np
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
X = iris.data
y = iris.target

print(X.shape, y.shape)

(150, 4) (150,)


In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [8]:
from sklearn.naive_bayes import GaussianNB

In [9]:
model = GaussianNB()

In [10]:
model.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [11]:
predictions = model.predict(X_test)

In [12]:
from sklearn.metrics import confusion_matrix, classification_report

In [13]:
print(confusion_matrix(y_test, predictions))

[[13  0  0]
 [ 0 19  1]
 [ 0  1 11]]


In [14]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.95      0.95      0.95        20
           2       0.92      0.92      0.92        12

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

